package presentacion;

public enum Evento {//lista eventos
	ALTA_MESA, BAJA_MESA, LISTAR_MESAS, BUSCAR_MESA, MODIFICAR_MESA, ALTA_MESA_OK, ALTA_MESA_KO, ALTA_MESA_VISTA, 
	ALTA_FACTURA, BUSCAR_FACTURA, MODIFICAR_FACTURA, LISTAR_FACTURAS, ALTA_LINEA_FACTURA, BUSCAR_LINEA_FACTURA, MODIFICAR_LINEA_FACTURA, LISTAR_LINEA_FACTURA,
	ALTA_PLATO, BAJA_PLATO, LISTAR_PLATOS, MODIFICAR_PLATOS, MODIFICAR_PLATO,
	
}
