package presentacion;

public enum Evento {//lista eventos
	ALTA_MESA, BAJA_MESA, LISTAR_MESAS, BUSCAR_MESA, MODIFICAR_MESA, ALTA_MESA_OK, ALTA_MESA_KO, ALTA_MESA_VISTA, BAJA_MESA_VISTA, BAJA_MESA_RES,
	ALTA_FACTURA, ALTA_FACTURA_VISTA, ALTA_FACTURA_VISTA_OK , ALTA_FACTURA_VISTA_WR, BUSCAR_FACTURA,BUSCAR_FACTURA_VISTA, BUSCAR_FACTURA_VISTA_OK , BUSCAR_FACTURA_VISTA_WR, MODIFICAR_FACTURA_VISTA_WR, MODIFICAR_FACTURA_VISTA, MODIFICAR_FACTURA_VISTA_OK,  MODIFICAR_FACTURA, LISTAR_FACTURAS, ANADIR_PRODUCTO, ANADIR_PRODUCTO_VISTA, ANADIR_PRODUCTO_VISTA_OK, ANADIR_PRODUCTO_VISTA_WR, ABRIR_VENTA, LISTAR_FACTURAS_VISTA,
	ALTA_PLATO, BAJA_PLATO, LISTAR_PLATOS, MODIFICAR_PLATO, 

	
}
